"""empty message

Revision ID: 53fc4e046f4c
Revises: 
Create Date: 2017-05-01 14:36:47.891959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53fc4e046f4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('calendar_url', sa.String(length=512), nullable=True))
    op.add_column('Users', sa.Column('registered_on', sa.DateTime(), nullable=True))
    op.drop_column('Users', 'registeredOn')
    op.drop_column('Users', 'calendarURL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('calendarURL', sa.VARCHAR(length=512), nullable=True))
    op.add_column('Users', sa.Column('registeredOn', sa.DATETIME(), nullable=True))
    op.drop_column('Users', 'registered_on')
    op.drop_column('Users', 'calendar_url')
    # ### end Alembic commands ###
